@baseapi = http://localhost:4000
@version = v1
@at = {{login.response.body.token}}
GET {{baseapi}} HTTP/1.1

### login
# @name login
POST {{baseapi}}/{{version}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"BKDev99",
    "pwd":"Dev1122"
}

### get data
POST {{baseapi}}/{{version}}/user/getData HTTP/1.1
Content-Type: application/json
authorization:  {{at}}

{
    "limit":10,
    "offset":0
}
### get data by uid
GET {{baseapi}}/{{version}}/user/getDataByUid/5 HTTP/1.1
Content-Type: application/json
authorization:  {{at}}


### update
PUT {{baseapi}}/{{version}}/user/edit HTTP/1.1
Content-Type: application/json
authorization:  {{at}}

{
    "name":"Bounkhong",
    "surname":"Chuangthevy",
    "gender":"m",
    "username":"BKDev",
    "pwd":"Dev99",
    "uid":4
}

### delete
DELETE {{baseapi}}/{{version}}/user/del/5 HTTP/1.1
Content-Type: application/json
authorization:  {{at}}